---
parameters:
    zeus.player.base_level: 1250
    zeus.player.base_commander_level: 100
    zeus.player.base_ap: 10
    zeus.player.coeff_ap: 5

    zeus.player.tax_coeff: 1

    zeus.player.active: 1
    zeus.player.inactive: 2
    zeus.player.holiday: 3
    zeus.player.banned: 4
    zeus.player.deleted: 5
    zeus.player.dead: 6

    zeus.player.standard: 1
    zeus.player.parliament: 2
    zeus.player.treasurer: 3
    zeus.player.warlord: 4
    zeus.player.minister: 5
    zeus.player.chief: 6

    zeus.player.ally_inactive_time: 24 * 7
    zeus.player.global_inactive_time: 24 * 15
    zeus.player.inactive_time_limit: 24 * 25

services:
    zeus.player_manager:
        class: Asylamba\Modules\Zeus\Manager\PlayerManager
        arguments:
            - "@database"
            - "@gaia.sector_manager"
            - "@hermes.notification_manager"
            - "@athena.orbital_base_manager"
            - "@gaia.place_manager"
    
    zeus.credit_transaction_manager:
        class: Asylamba\Modules\Zeus\Manager\CreditTransactionManager
        arguments:
            - "@database"
            
    zeus.check_name_helper:
        class: Asylamba\Modules\Zeus\Helper\CheckName
        
    zeus.player_helper:
        class: Asylamba\Modules\Zeus\Helper\PlayerHelper
        arguments:
            - "@database"
            
    zeus.tutorial_helper:
        class: Asylamba\Modules\Zeus\Helper\TutorialHelper
        arguments:
            - "@zeus.player_manager"
            - "@athena.orbital_base_manager"
            - "@athena.building_queue_manager"
            - "@promethee.technology_queue_manager"
         