---
services:
    database:
        class: Asylamba\Classes\Database\Database
        arguments:
            - "%database_host"
            - "%database_name"
            - "%database_user"
            - "%database_password"
            
    database_admin:
        class: Asylamba\Classes\Database\DatabaseAdmin
        arguments:
            - "%database_host"
            - "%database_name"
            - "%database_admin_user"
            - "%database_admin_password"
            
    session_wrapper:
        class: Asylamba\Classes\Library\Session\SessionWrapper
            
    cyclic_action_scheduler:
        class: Asylamba\Classes\Scheduler\CyclicActionScheduler
        arguments:
            - "@app.container"
            
    realtime_action_scheduler:
        class: Asylamba\Classes\Scheduler\RealTimeActionScheduler
        arguments:
            - "@app.container"
            
    router:
        class: Asylamba\Classes\Router\Router
        arguments:
            - "@session_wrapper"
        
    request_factory:
        class: Asylamba\Classes\Library\Http\RequestFactory
        
    response_factory:
        class: Asylamba\Classes\Library\Http\ResponseFactory
        arguments:
            - "@templating.renderer"
            - "@session_wrapper"
        
    client_manager:
        class: Asylamba\Classes\Daemon\ClientManager
        arguments:
            - "%session_lifetime"
        
    templating.renderer:
        class: Asylamba\Classes\Templating\Renderer
        arguments:
            - "@app.container"
            
    server:
        class: Asylamba\Classes\Daemon\Server
        arguments:
            - "@app.container"
            
    entity_manager:
        class: Asylamba\Classes\Entity\EntityManager
        arguments:
            - "@database"
            
    event_dispatcher:
        class: Asylamba\Classes\Worker\EventDispatcher
        arguments:
            - "@app.container"
            
    logger:
        class: "%log_handler"
        arguments:
            - "%log_directory"
            - "%log_rotation"
            
    parser:
        class: Asylamba\Classes\Library\Parser
        arguments:
            - "@gaia.place_manager"
            - "@zeus.player_manager"

    security:
        class: Asylamba\Classes\Library\Security
        arguments:
            - "@session_wrapper"
        
    ctc:
        class: Asylamba\Classes\Worker\CTC
        arguments:
            - "@session_wrapper"
            - "%root_path"
        
    exception_listener:
        class: Asylamba\Classes\EventListener\ExceptionListener
        arguments:
            - "@logger"
            - "@session_wrapper"
        tags:
            - {type: "event_listener", event: "core.exception", method: "onCoreException"}
            - {type: "event_listener", event: "core.error", method: "onCoreError"}
