---
parameters:
    promethee.research.coeff: 1
    promethee.research.max_diff: 3
    promethee.research._quantity: 10

    promethee.technology_queue.resource_refund: 0.5
    promethee.technology_queue.credit_refund: 0.5    
    
services:
    promethee.research_manager:
        class: Asylamba\Modules\Promethee\Manager\ResearchManager
        arguments:
            - "@database"
            
    promethee.technology_manager:
        class: Asylamba\Modules\Promethee\Manager\TechnologyManager
        arguments:
            - "@database"
            - "@zeus.player_bonus_manager"
            
    promethee.technology_queue_manager:
        class: Asylamba\Modules\Promethee\Manager\TechnologyQueueManager
        arguments:
            - "@database"
